name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Write Impressum.md from secret
        run: |
          echo "$IMPRESSUM_MD" > ./docs/impressum.md
        env:
          IMPRESSUM_MD: ${{ secrets.IMPRESSUM_MD }}

      - name: Write Datenschutz.md from secret
        run: |
          echo "$DATENSCHUTZ_MD" > ./docs/datenschutz.md
        env:
          DATENSCHUTZ_MD: ${{ secrets.DATENSCHUTZ_MD }}

      - name: Install Dependencies
        run: npm install
        working-directory: ./docs

      - name: Build VitePress Site
        run: npm run build
        working-directory: ./docs

      - name: List Build Files
        run: ls -l ./docs/.vitepress/dist

      - name: Copy Build to Webroot
        run: cp -r ./docs/.vitepress/dist/* /var/www/it-systemtechnik.at/
